# Generated by Django 6.0.2 on 2026-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketprice',
            options={'ordering': ['name'], 'verbose_name': 'Тариф / услуга', 'verbose_name_plural': 'Тарифы / услуги'},
        ),
        migrations.AddField(
            model_name='ticketprice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='ticketprice',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='services/', verbose_name='Изображение'),
        ),
    ]
