# Generated by Django 6.0.2 on 2026-08-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_alter_ticketprice_options_ticketprice_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='dating',
            field=models.CharField(blank=True, max_length=100, verbose_name='Датировка'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Инвентарный номер'),
        ),
        migrations.AddField(
            model_name='tour',
            name='audience',
            field=models.CharField(blank=True, max_length=200, verbose_name='Целевая аудитория'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Длительность (мин.)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость (BYN)'),
        ),
    ]
