# Generated by Django 6.0.2 on 2026-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('title', models.CharField(max_length=300, verbose_name='Событие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Историческое событие',
                'verbose_name_plural': 'История по годам',
                'ordering': ['year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Музей искусств', max_length=300, verbose_name='Название организации')),
                ('logo', models.FileField(blank=True, null=True, upload_to='company/', verbose_name='Логотип')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='company/video/', verbose_name='Видео')),
                ('video_url', models.URLField(blank=True, verbose_name='URL видео (iframe)')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='company/audio/', verbose_name='Аудиогид / аудио')),
                ('requisites', models.TextField(blank=True, verbose_name='Реквизиты')),
                ('certificate_text', models.TextField(blank=True, verbose_name='Сертификат (текст без стилей)')),
                ('map_embed_url', models.URLField(blank=True, default='https://www.openstreetmap.org/export/embed.html?bbox=27.55%2C53.89%2C27.57%2C53.91&layer=mapnik', verbose_name='URL карты (iframe)')),
            ],
            options={
                'verbose_name': 'Профиль компании',
                'verbose_name_plural': 'Профиль компании',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.FileField(blank=True, null=True, upload_to='partners/', verbose_name='Логотип')),
                ('website_url', models.URLField(verbose_name='Сайт')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['order', 'name'],
            },
        ),
    ]
